#!/usr/bin/env bash

set -xeuo pipefail

rm -f ~/.rvm/rubies/ruby-*/bin/bundle
gem update --system --force --no-document
gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
gem install bundler -v '< 2' --no-document
bundle config set path vendor/bundle
